name: Check Python base image

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Verify python:3.12-slim digest
        run: |
          set -euo pipefail
          docker pull python:3.12-slim > /dev/null
          DIGEST=$(docker image inspect python:3.12-slim --format '{{index .RepoDigests 0}}' | cut -d@ -f2)
          if [ "$DIGEST" != "sha256:6d09f05f9bebe88e6100f8feaf8b7eaacf7d5005c45e26dfec66f64fdf75f1a4" ]; then
            echo "Expected sha256:6d09f05f9bebe88e6100f8feaf8b7eaacf7d5005c45e26dfec66f64fdf75f1a4 but got $DIGEST"
            exit 1
          fi
          echo "Digest up to date: $DIGEST"

